# .prettierrc or .prettierrc.yaml
trailingComma: 'es5'
tabWidth: 2
semi: false
singleQuote: true
jsxSingleQuote: true
bracketSameLine: true
arrowParens: 'avoid'
singleAttributePerLine: true
organizeImports: true
